import localFont from "next/font/local";
import "./globals.css";
import { MantineProvider, ColorSchemeScript } from "@mantine/core"; 
// import { NotificationsProvider } from "@mantine/notifications";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logoTabXapiens.png" />
        <ColorSchemeScript />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* {children} */}
        <MantineProvider withGlobalStyles withNormalizeCSS>
          {/* <NotificationsProvider> */}
            {" "}
            {children}
          {/* </NotificationsProvider> */}
        </MantineProvider>
      </body>
    </html>
  );
}
